/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import DAO.TransactionDAO;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.User;
import services.UserService;
import utils.Session;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.io.File;
import java.math.BigDecimal;
import java.text.NumberFormat;
import java.util.Locale;

/**
 *
 * @author Arch Salon
 */
public class AccountPanel extends javax.swing.JPanel {

    /**
     * Creates new form AccountPanel
     */
    public AccountPanel() {
        initComponents();
        loadStatistics();

        java.awt.EventQueue.invokeLater(() -> {
            loadUserInfo();
        });
    }

    private void loadStatistics() {

        try {

            TransactionDAO dao = new TransactionDAO();

            int userId = Session.getCurrentUser().getId();

            BigDecimal income = dao.getTotalByType(userId, "income");
            BigDecimal expense = dao.getTotalByType(userId, "expense");

            BigDecimal balance = income.subtract(expense);

            int transactionCount = dao.getTransactionCount(userId);
            int categoryCount = dao.getCategoryCount(userId);

            // 👇 Paste it here
            NumberFormat peso = NumberFormat.getCurrencyInstance(new Locale("en", "PH"));

            lblTotalIncome.setText(peso.format(income));
            lblTotalExpense.setText(peso.format(expense));
            lblBalance.setText(peso.format(balance));

            lblTransactionCount.setText(String.valueOf(transactionCount));
            lblCategoryCount.setText(String.valueOf(categoryCount));

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadUserInfo() {

        User user = Session.getCurrentUser();

        if (user != null) {

            useridfield.setText(String.format("%04d", user.getId()));
            namefield.setText(user.getFullname());   // Use your actual field name
            usernamefield.setText(user.getUsername());
            emailfield.setText(user.getEmail());
            phonefield.setText(user.getPhone());
            agefield.setText(String.valueOf(user.getAge()));

            if (user.getProfilePicture() != null && !user.getProfilePicture().isEmpty()) {

                File imageFile = new File(user.getProfilePicture());

                if (imageFile.exists()) {

                    ImageIcon icon = new ImageIcon(imageFile.getAbsolutePath());

                    Image image = icon.getImage().getScaledInstance(
                            150,
                            150,
                            Image.SCALE_SMOOTH);

                    lblProfilePicture.setIcon(new ImageIcon(image));
                }
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sideBarPanel1 = new javax.swing.JPanel();
        jFrame1 = new javax.swing.JFrame();
        jLabel4 = new javax.swing.JLabel();
        sideBarPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblProfilePicture = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        usernamefield = new javax.swing.JTextField();
        namefield = new javax.swing.JTextField();
        agefield = new javax.swing.JTextField();
        useridfield = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        emailfield = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        phonefield = new javax.swing.JTextField();
        btnUploadPicture = new javax.swing.JButton();
        btnEditDetails = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        sideBarPanel2 = new javax.swing.JPanel();
        lblIncomeTitle = new javax.swing.JLabel();
        lblExpenseTitle = new javax.swing.JLabel();
        lblBalanceTitle = new javax.swing.JLabel();
        lblTransactionsTitle = new javax.swing.JLabel();
        lblCategoriesTitle = new javax.swing.JLabel();
        lblTotalIncome = new javax.swing.JLabel();
        lblTotalExpense = new javax.swing.JLabel();
        lblBalance = new javax.swing.JLabel();
        lblTransactionCount = new javax.swing.JLabel();
        lblCategoryCount = new javax.swing.JLabel();

        sideBarPanel1.setBackground(new java.awt.Color(111, 151, 143));

        javax.swing.GroupLayout sideBarPanel1Layout = new javax.swing.GroupLayout(sideBarPanel1);
        sideBarPanel1.setLayout(sideBarPanel1Layout);
        sideBarPanel1Layout.setHorizontalGroup(
            sideBarPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 268, Short.MAX_VALUE)
        );
        sideBarPanel1Layout.setVerticalGroup(
            sideBarPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Name:");

        setBackground(new java.awt.Color(220, 232, 208));
        setEnabled(false);
        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                formAncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        sideBarPanel.setBackground(new java.awt.Color(111, 151, 143));
        sideBarPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jPanel1.setPreferredSize(new java.awt.Dimension(150, 150));

        lblProfilePicture.setPreferredSize(new java.awt.Dimension(150, 150));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblProfilePicture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblProfilePicture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Username:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Name:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("User ID:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Age:");

        usernamefield.setBackground(new java.awt.Color(111, 151, 143));
        usernamefield.setFont(new java.awt.Font("SansSerif", 1, 17)); // NOI18N
        usernamefield.setBorder(null);
        usernamefield.setEnabled(false);

        namefield.setBackground(new java.awt.Color(111, 151, 143));
        namefield.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        namefield.setForeground(new java.awt.Color(255, 255, 255));
        namefield.setBorder(null);
        namefield.setEnabled(false);

        agefield.setEditable(false);
        agefield.setBackground(new java.awt.Color(111, 151, 143));
        agefield.setFont(new java.awt.Font("SansSerif", 1, 17)); // NOI18N
        agefield.setBorder(null);
        agefield.setEnabled(false);
        agefield.addActionListener(this::agefieldActionPerformed);

        useridfield.setEditable(false);
        useridfield.setBackground(new java.awt.Color(111, 151, 143));
        useridfield.setFont(new java.awt.Font("SansSerif", 1, 17)); // NOI18N
        useridfield.setBorder(null);
        useridfield.setEnabled(false);
        useridfield.addActionListener(this::useridfieldActionPerformed);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Email:");

        emailfield.setBackground(new java.awt.Color(111, 151, 143));
        emailfield.setFont(new java.awt.Font("SansSerif", 1, 17)); // NOI18N
        emailfield.setBorder(null);
        emailfield.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("Phone:");

        phonefield.setBackground(new java.awt.Color(111, 151, 143));
        phonefield.setFont(new java.awt.Font("SansSerif", 1, 17)); // NOI18N
        phonefield.setBorder(null);
        phonefield.setEnabled(false);

        btnUploadPicture.setBackground(new java.awt.Color(204, 204, 204));
        btnUploadPicture.setText("Upload Picture");
        btnUploadPicture.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnUploadPicture.addActionListener(this::btnUploadPictureActionPerformed);

        btnEditDetails.setBackground(new java.awt.Color(204, 204, 204));
        btnEditDetails.setText("Edit Details");
        btnEditDetails.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnEditDetails.addActionListener(this::btnEditDetailsActionPerformed);

        javax.swing.GroupLayout sideBarPanelLayout = new javax.swing.GroupLayout(sideBarPanel);
        sideBarPanel.setLayout(sideBarPanelLayout);
        sideBarPanelLayout.setHorizontalGroup(
            sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEditDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUploadPicture, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 22, Short.MAX_VALUE)
                .addGroup(sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sideBarPanelLayout.createSequentialGroup()
                        .addGroup(sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(namefield, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                            .addComponent(usernamefield)))
                    .addGroup(sideBarPanelLayout.createSequentialGroup()
                        .addGroup(sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(58, 58, 58)
                        .addGroup(sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(useridfield, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agefield, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)))
                .addGroup(sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sideBarPanelLayout.createSequentialGroup()
                        .addGroup(sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sideBarPanelLayout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(jLabel7))
                            .addGroup(sideBarPanelLayout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(jLabel8)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sideBarPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addGroup(sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sideBarPanelLayout.createSequentialGroup()
                                .addComponent(emailfield, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sideBarPanelLayout.createSequentialGroup()
                                .addComponent(phonefield, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(170, 170, 170))))))
        );
        sideBarPanelLayout.setVerticalGroup(
            sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(sideBarPanelLayout.createSequentialGroup()
                        .addGroup(sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(namefield, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(usernamefield, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailfield, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(useridfield, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(14, 14, 14)
                        .addGroup(sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(agefield, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phonefield, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUploadPicture)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEditDetails)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(111, 151, 143));
        jLabel1.setText("My Account");

        sideBarPanel2.setBackground(new java.awt.Color(111, 151, 143));
        sideBarPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        lblIncomeTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblIncomeTitle.setForeground(new java.awt.Color(0, 102, 102));
        lblIncomeTitle.setText("Total Income");

        lblExpenseTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblExpenseTitle.setForeground(new java.awt.Color(0, 102, 102));
        lblExpenseTitle.setText("Total Expenses");

        lblBalanceTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblBalanceTitle.setForeground(new java.awt.Color(0, 102, 102));
        lblBalanceTitle.setText("Current Balance ");

        lblTransactionsTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTransactionsTitle.setForeground(new java.awt.Color(0, 102, 102));
        lblTransactionsTitle.setText("Transactions");

        lblCategoriesTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCategoriesTitle.setForeground(new java.awt.Color(0, 102, 102));
        lblCategoriesTitle.setText("Categories Used");

        lblTotalIncome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTotalIncome.setForeground(new java.awt.Color(0, 102, 102));
        lblTotalIncome.setText("0.00");

        lblTotalExpense.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTotalExpense.setForeground(new java.awt.Color(0, 102, 102));
        lblTotalExpense.setText("0.00");

        lblBalance.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblBalance.setForeground(new java.awt.Color(0, 102, 102));
        lblBalance.setText("0.00");

        lblTransactionCount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTransactionCount.setForeground(new java.awt.Color(0, 102, 102));
        lblTransactionCount.setText("0");

        lblCategoryCount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCategoryCount.setForeground(new java.awt.Color(0, 102, 102));
        lblCategoryCount.setText("0");

        javax.swing.GroupLayout sideBarPanel2Layout = new javax.swing.GroupLayout(sideBarPanel2);
        sideBarPanel2.setLayout(sideBarPanel2Layout);
        sideBarPanel2Layout.setHorizontalGroup(
            sideBarPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarPanel2Layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addGroup(sideBarPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIncomeTitle)
                    .addComponent(lblExpenseTitle)
                    .addComponent(lblBalanceTitle)
                    .addComponent(lblTransactionsTitle)
                    .addComponent(lblCategoriesTitle))
                .addGap(150, 150, 150)
                .addGroup(sideBarPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBalance)
                    .addComponent(lblTotalExpense)
                    .addComponent(lblTotalIncome)
                    .addGroup(sideBarPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblCategoryCount)
                        .addComponent(lblTransactionCount)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sideBarPanel2Layout.setVerticalGroup(
            sideBarPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(sideBarPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalIncome)
                    .addComponent(lblIncomeTitle))
                .addGap(18, 18, 18)
                .addGroup(sideBarPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExpenseTitle)
                    .addComponent(lblTotalExpense))
                .addGap(18, 18, 18)
                .addGroup(sideBarPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBalanceTitle)
                    .addComponent(lblBalance))
                .addGap(18, 18, 18)
                .addGroup(sideBarPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTransactionCount)
                    .addComponent(lblTransactionsTitle))
                .addGap(18, 18, 18)
                .addGroup(sideBarPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoriesTitle)
                    .addComponent(lblCategoryCount))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(sideBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sideBarPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(jLabel1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sideBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sideBarPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_formAncestorMoved

    private void useridfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useridfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_useridfieldActionPerformed

    private void agefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agefieldActionPerformed

    private void btnUploadPictureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadPictureActionPerformed

        JFileChooser chooser = new JFileChooser();

        int result = chooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {

            File selectedFile = chooser.getSelectedFile();

            User user = Session.getCurrentUser();

            // Create the destination file name
            String destination = "profile_pictures/"
                    + String.format("%04d", user.getId()) + ".png";

            try {

                File folder = new File("profile_pictures");

                if (!folder.exists()) {
                    folder.mkdirs();
                }

                File destinationFile = new File(folder,
                        String.format("%04d.png", user.getId()));

                Files.copy(
                        selectedFile.toPath(),
                        destinationFile.toPath(),
                        StandardCopyOption.REPLACE_EXISTING
                );

                String imagePath = destinationFile.getPath();

                UserService service = new UserService();

                service.updateProfilePicture(user.getId(), imagePath);

                user.setProfilePicture(imagePath);

                JOptionPane.showMessageDialog(this,
                        "Profile picture uploaded successfully!");

            } catch (IOException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, e.toString());
            }
        }
    }//GEN-LAST:event_btnUploadPictureActionPerformed

    private void btnEditDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditDetailsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField agefield;
    private javax.swing.JButton btnEditDetails;
    private javax.swing.JButton btnUploadPicture;
    private javax.swing.JTextField emailfield;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblBalanceTitle;
    private javax.swing.JLabel lblCategoriesTitle;
    private javax.swing.JLabel lblCategoryCount;
    private javax.swing.JLabel lblExpenseTitle;
    private javax.swing.JLabel lblIncomeTitle;
    private javax.swing.JLabel lblProfilePicture;
    private javax.swing.JLabel lblTotalExpense;
    private javax.swing.JLabel lblTotalIncome;
    private javax.swing.JLabel lblTransactionCount;
    private javax.swing.JLabel lblTransactionsTitle;
    private javax.swing.JTextField namefield;
    private javax.swing.JTextField phonefield;
    private javax.swing.JPanel sideBarPanel;
    private javax.swing.JPanel sideBarPanel1;
    private javax.swing.JPanel sideBarPanel2;
    private javax.swing.JTextField useridfield;
    private javax.swing.JTextField usernamefield;
    // End of variables declaration//GEN-END:variables
}
