/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import DAO.TransactionDAO;
import DAO.UserDAO;
import Utils.ThemeManager;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.User;
import services.UserService;
import utils.Session;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.awt.Window;
import java.io.File;
import java.math.BigDecimal;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.mindrot.jbcrypt.BCrypt;
import java.sql.SQLException;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Arch Salon
 */
public class AccountPanelDark extends javax.swing.JPanel {

    // Reference to HomeFrame
    private HomeFrame homeFrame;

    /**
     * Creates new form AccountPanel
     */
    public AccountPanelDark() {

        initComponents();

        chkDarkMode.setSelected(ThemeManager.isDarkMode());

        java.awt.EventQueue.invokeLater(() -> {
            loadUserInfo();
        });
    }

    private void loadUserInfo() {

        User user = Session.getCurrentUser();

        if (user != null) {

            useridfield.setText(String.format("%04d", user.getId()));
            namefield.setText(user.getFullname());   // Use your actual field name
            usernamefield.setText(user.getUsername());
            emailfield.setText(user.getEmail());
            phonefield.setText(user.getPhone());
            agefield.setText(String.valueOf(user.getAge()));

            if (user.getProfilePicture() != null && !user.getProfilePicture().isEmpty()) {

                File imageFile = new File(user.getProfilePicture());

                if (imageFile.exists()) {

                    ImageIcon icon = new ImageIcon(imageFile.getAbsolutePath());

                    Image image = icon.getImage().getScaledInstance(
                            150,
                            150,
                            Image.SCALE_SMOOTH);

                    lblProfilePicture.setIcon(new ImageIcon(image));
                }
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sideBarPanel1 = new javax.swing.JPanel();
        jFrame1 = new javax.swing.JFrame();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlProfileCard = new javax.swing.JPanel();
        lblProfilePicture = new javax.swing.JLabel();
        btnUploadPicture = new javax.swing.JButton();
        namefield = new javax.swing.JLabel();
        usernamefield = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        emailfield = new javax.swing.JLabel();
        email1 = new javax.swing.JLabel();
        agefield = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        phonefield = new javax.swing.JLabel();
        useridfield = new javax.swing.JLabel();
        userid = new javax.swing.JLabel();
        pnlSettings = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        chkDarkMode = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        ChangeDetails = new javax.swing.JButton();
        ChangePassword = new javax.swing.JButton();
        DeleteAccount = new javax.swing.JButton();

        sideBarPanel1.setBackground(new java.awt.Color(111, 151, 143));

        javax.swing.GroupLayout sideBarPanel1Layout = new javax.swing.GroupLayout(sideBarPanel1);
        sideBarPanel1.setLayout(sideBarPanel1Layout);
        sideBarPanel1Layout.setHorizontalGroup(
            sideBarPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 268, Short.MAX_VALUE)
        );
        sideBarPanel1Layout.setVerticalGroup(
            sideBarPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Name:");

        setBackground(new java.awt.Color(220, 232, 208));
        setEnabled(false);
        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                formAncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("My Account");
        jLabel1.setAlignmentX(35.0F);
        jLabel1.setAlignmentY(20.0F);

        pnlProfileCard.setBackground(new java.awt.Color(0, 51, 51));
        pnlProfileCard.setAlignmentX(35.0F);
        pnlProfileCard.setAlignmentY(70.0F);

        lblProfilePicture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProfilePicture.setText("Profile Picture");
        lblProfilePicture.setPreferredSize(new java.awt.Dimension(150, 150));

        btnUploadPicture.setBackground(new java.awt.Color(0, 51, 51));
        btnUploadPicture.setForeground(new java.awt.Color(255, 255, 255));
        btnUploadPicture.setText("Upload Picture");
        btnUploadPicture.addActionListener(this::btnUploadPictureActionPerformed);

        namefield.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        namefield.setForeground(new java.awt.Color(47, 72, 88));
        namefield.setText("FULL NAME");

        usernamefield.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        usernamefield.setForeground(new java.awt.Color(153, 153, 153));
        usernamefield.setText("@username");

        email.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        email.setForeground(new java.awt.Color(47, 72, 88));
        email.setText("EMAIL");

        emailfield.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        emailfield.setForeground(new java.awt.Color(153, 153, 153));
        emailfield.setText("admin@email.com");

        email1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        email1.setForeground(new java.awt.Color(47, 72, 88));
        email1.setText("AGE");

        agefield.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        agefield.setForeground(new java.awt.Color(153, 153, 153));
        agefield.setText("24");

        phone.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        phone.setForeground(new java.awt.Color(47, 72, 88));
        phone.setText("PHONE NUMBER");

        phonefield.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        phonefield.setForeground(new java.awt.Color(153, 153, 153));
        phonefield.setText("09667616822 ");

        useridfield.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        useridfield.setForeground(new java.awt.Color(153, 153, 153));
        useridfield.setText("0009   ");

        userid.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        userid.setForeground(new java.awt.Color(47, 72, 88));
        userid.setText("USER ID");

        javax.swing.GroupLayout pnlProfileCardLayout = new javax.swing.GroupLayout(pnlProfileCard);
        pnlProfileCard.setLayout(pnlProfileCardLayout);
        pnlProfileCardLayout.setHorizontalGroup(
            pnlProfileCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProfileCardLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlProfileCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProfilePicture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUploadPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(pnlProfileCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProfileCardLayout.createSequentialGroup()
                        .addGroup(pnlProfileCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usernamefield, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namefield, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlProfileCardLayout.createSequentialGroup()
                        .addGroup(pnlProfileCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(email)
                            .addGroup(pnlProfileCardLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(pnlProfileCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(agefield, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(email1)))
                            .addComponent(emailfield, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlProfileCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProfileCardLayout.createSequentialGroup()
                                .addComponent(phone)
                                .addGap(66, 66, 66))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProfileCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(userid)
                                .addComponent(phonefield, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(useridfield, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(58, 58, 58))))
        );
        pnlProfileCardLayout.setVerticalGroup(
            pnlProfileCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProfileCardLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnlProfileCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProfileCardLayout.createSequentialGroup()
                        .addComponent(lblProfilePicture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUploadPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlProfileCardLayout.createSequentialGroup()
                        .addGroup(pnlProfileCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(useridfield)
                            .addGroup(pnlProfileCardLayout.createSequentialGroup()
                                .addComponent(phone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(phonefield)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(userid)
                                .addGap(42, 42, 42))
                            .addGroup(pnlProfileCardLayout.createSequentialGroup()
                                .addComponent(namefield)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(usernamefield)
                                .addGap(10, 10, 10)
                                .addComponent(email)
                                .addGap(2, 2, 2)
                                .addComponent(emailfield)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(email1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(agefield)))
                        .addGap(0, 8, Short.MAX_VALUE))))
        );

        pnlSettings.setBackground(new java.awt.Color(0, 51, 51));
        pnlSettings.setAlignmentX(35.0F);
        pnlSettings.setAlignmentY(330.0F);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Account Settings");
        jLabel2.setAlignmentX(35.0F);
        jLabel2.setAlignmentY(20.0F);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Appearance");

        chkDarkMode.setBackground(new java.awt.Color(204, 204, 204));
        chkDarkMode.setText("DarkMode");
        chkDarkMode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chkDarkMode.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        chkDarkMode.addActionListener(this::chkDarkModeActionPerformed);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Account");

        ChangeDetails.setBackground(new java.awt.Color(0, 102, 102));
        ChangeDetails.setText("Edit Details");
        ChangeDetails.addActionListener(this::ChangeDetailsActionPerformed);

        ChangePassword.setBackground(new java.awt.Color(0, 102, 102));
        ChangePassword.setText("Change Passoword");
        ChangePassword.addActionListener(this::ChangePasswordActionPerformed);

        DeleteAccount.setBackground(new java.awt.Color(255, 153, 153));
        DeleteAccount.setText("Delete Account!");
        DeleteAccount.addActionListener(this::DeleteAccountActionPerformed);

        javax.swing.GroupLayout pnlSettingsLayout = new javax.swing.GroupLayout(pnlSettings);
        pnlSettings.setLayout(pnlSettingsLayout);
        pnlSettingsLayout.setHorizontalGroup(
            pnlSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSettingsLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(39, 39, 39))
            .addGroup(pnlSettingsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addGroup(pnlSettingsLayout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addGroup(pnlSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(DeleteAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ChangePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ChangeDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel3))
                    .addComponent(chkDarkMode, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSettingsLayout.setVerticalGroup(
            pnlSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSettingsLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkDarkMode, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ChangeDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ChangePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(DeleteAccount)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(344, 344, 344)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlProfileCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(pnlSettings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlProfileCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_formAncestorMoved

    private void ChangeDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeDetailsActionPerformed
        User currentUser = Session.getCurrentUser();

        String fullname = JOptionPane.showInputDialog(
                this,
                "Full Name:",
                currentUser.getFullname());

        if (fullname == null) {
            return;
        }

        String email = JOptionPane.showInputDialog(
                this,
                "Email:",
                currentUser.getEmail());

        if (email == null) {
            return;
        }

        String phone = JOptionPane.showInputDialog(
                this,
                "Phone:",
                currentUser.getPhone());

        if (phone == null) {
            return;
        }

        String ageText = JOptionPane.showInputDialog(
                this,
                "Age:",
                currentUser.getAge());

        if (ageText == null) {
            return;
        }

        try {

            int age = Integer.parseInt(ageText);

            currentUser.setFullname(fullname.trim());
            currentUser.setEmail(email.trim());
            currentUser.setPhone(phone.trim());
            currentUser.setAge(age);

            UserService service = new UserService();

            if (service.updateUser(currentUser)) {

                loadUserInfo();

                JOptionPane.showMessageDialog(
                        this,
                        "Details updated successfully!");

            } else {

                JOptionPane.showMessageDialog(
                        this,
                        "Unable to update details.");

            }

        } catch (NumberFormatException ex) {

            JOptionPane.showMessageDialog(
                    this,
                    "Age must be a valid number.");

        }

    }//GEN-LAST:event_ChangeDetailsActionPerformed

    private void ChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangePasswordActionPerformed
        // Ask for the current password
        String currentPassword = JOptionPane.showInputDialog(
                this,
                "Enter current password:");

        if (currentPassword == null) {
            return;
        }

        // Ask for the new password
        String newPassword = JOptionPane.showInputDialog(
                this,
                "Enter new password:");

        if (newPassword == null) {
            return;
        }

        // Ask to confirm the new password
        String confirmPassword = JOptionPane.showInputDialog(
                this,
                "Confirm new password:");

        if (confirmPassword == null) {
            return;
        }

        // Get the currently logged-in user
        User user = Session.getCurrentUser();

        // Verify that the current password is correct
        if (!BCrypt.checkpw(currentPassword, user.getPassword())) {

            JOptionPane.showMessageDialog(
                    this,
                    "Current password is incorrect.");

            return;
        }

        // Check if the new passwords match
        if (!newPassword.equals(confirmPassword)) {

            JOptionPane.showMessageDialog(
                    this,
                    "Passwords do not match.");

            return;
        }

        // Check if the password meets the minimum length
        if (newPassword.length() < 8) {

            JOptionPane.showMessageDialog(
                    this,
                    "Password must be at least 8 characters.");

            return;
        }

        // Hash the new password using BCrypt
        String hashedPassword = BCrypt.hashpw(
                newPassword,
                BCrypt.gensalt());

        // Create the service object
        UserService service = new UserService();

        // Save the new password
        if (service.changePassword(user.getId(), hashedPassword)) {

            // Update the password stored in the current session
            user.setPassword(hashedPassword);

            JOptionPane.showMessageDialog(
                    this,
                    "Password changed successfully!");

        } else {

            JOptionPane.showMessageDialog(
                    this,
                    "Unable to change password.");

        }
    }//GEN-LAST:event_ChangePasswordActionPerformed

    private void btnUploadPictureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadPictureActionPerformed

        // Open a file chooser
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Select Profile Picture");

        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "Image Files", "jpg", "jpeg", "png");
        chooser.setFileFilter(filter);

        int result = chooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {

            File selectedFile = chooser.getSelectedFile();

            // Resize and display the selected image
            ImageIcon icon = new ImageIcon(selectedFile.getAbsolutePath());
            Image image = icon.getImage().getScaledInstance(
                    150,
                    150,
                    Image.SCALE_SMOOTH);

            lblProfilePicture.setIcon(new ImageIcon(image));

            User user = Session.getCurrentUser();

            if (user != null) {

                try {

                    // Save the image path to the database
                    UserDAO userDAO = new UserDAO();

                    boolean success = userDAO.updateProfilePicture(
                            user.getId(),
                            selectedFile.getAbsolutePath());

                    if (success) {

                        // Update the current session
                        user.setProfilePicture(selectedFile.getAbsolutePath());

                        JOptionPane.showMessageDialog(
                                this,
                                "Profile picture updated successfully!");

                    } else {

                        JOptionPane.showMessageDialog(
                                this,
                                "Failed to update profile picture.");

                    }

                } catch (SQLException ex) {

                    ex.printStackTrace();

                    JOptionPane.showMessageDialog(
                            this,
                            "Error updating profile picture.");

                }
            }
        }
    }//GEN-LAST:event_btnUploadPictureActionPerformed

    private void DeleteAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteAccountActionPerformed
// Ask for the first confirmation
        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to delete your account?",
                "Delete Account",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

// Ask for the second confirmation
        confirm = JOptionPane.showConfirmDialog(
                this,
                "Are you very sure?\n\nThis action cannot be undone.",
                "Delete Account",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

// Ask for the third confirmation
        confirm = JOptionPane.showConfirmDialog(
                this,
                "Are you REALLY sure?\n\nYour account and all of your expense records will be permanently deleted.",
                "Delete Account",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

// Ask for the final confirmation
        confirm = JOptionPane.showConfirmDialog(
                this,
                "Last chance!\n\nOnce you continue, there is no way to recover your account.\n\nDelete your account forever?",
                "Final Confirmation",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.ERROR_MESSAGE);

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

// Delete the account here
    }//GEN-LAST:event_DeleteAccountActionPerformed

    private void chkDarkModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDarkModeActionPerformed

        ThemeManager.setDarkMode(chkDarkMode.isSelected());

        // Let the user know what's happening
        JOptionPane.showMessageDialog(
                this,
                "The application will reload to apply the selected theme.",
                "Theme Changed",
                JOptionPane.INFORMATION_MESSAGE
        );

        // Close the current window
        Window window = SwingUtilities.getWindowAncestor(this);
        window.dispose();

        // Open the correct HomeFrame
        if (ThemeManager.isDarkMode()) {

            HomeFrameDark frame = new HomeFrameDark();
            frame.setVisible(true);
            frame.openAccountPanel();

        } else {

            HomeFrame frame = new HomeFrame();
            frame.setVisible(true);
            frame.openAccountPanel();

        }
    }//GEN-LAST:event_chkDarkModeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChangeDetails;
    private javax.swing.JButton ChangePassword;
    private javax.swing.JButton DeleteAccount;
    private javax.swing.JLabel agefield;
    private javax.swing.JButton btnUploadPicture;
    private javax.swing.JCheckBox chkDarkMode;
    private javax.swing.JLabel email;
    private javax.swing.JLabel email1;
    private javax.swing.JLabel emailfield;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblProfilePicture;
    private javax.swing.JLabel namefield;
    private javax.swing.JLabel phone;
    private javax.swing.JLabel phonefield;
    private javax.swing.JPanel pnlProfileCard;
    private javax.swing.JPanel pnlSettings;
    private javax.swing.JPanel sideBarPanel1;
    private javax.swing.JLabel userid;
    private javax.swing.JLabel useridfield;
    private javax.swing.JLabel usernamefield;
    // End of variables declaration//GEN-END:variables
}
