package GUI;

import java.awt.Dimension;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Category;
import model.Transaction;
import services.CategoryService;
import services.TransactionService;
import utils.Session;

public class IncomePanel extends javax.swing.JPanel {
    private int selectedTransactionId = -1;

    public IncomePanel() {
        initComponents();
        //setPreferredSize(new Dimension(1024,600));
        loadIncomeCategories();
        loadIncomeTable();
        
        incomeTable.getColumnModel().getColumn(0).setMinWidth(0);
        incomeTable.getColumnModel().getColumn(0).setMaxWidth(0);
        incomeTable.getColumnModel().getColumn(0).setPreferredWidth(0);
    }
    
    private void loadIncomeCategories() {
        CategoryService service = new CategoryService();
        int userId = Session.getCurrentUser().getId();
        ArrayList<Category> categories = service.getCategories(userId, "income");

        cmboIncomeCategory.removeAllItems();

        for (Category category : categories) {
            cmboIncomeCategory.addItem(category);
        }
    }
    
    private void loadIncomeTable() {
        DefaultTableModel model = (DefaultTableModel) incomeTable.getModel();
        model.setRowCount(0);

        TransactionService transactionService = new TransactionService();
        CategoryService categoryService = new CategoryService();

        int userId = Session.getCurrentUser().getId();

        List<Transaction> transactions = transactionService.getTransactionsByType(userId, "income");

        for (Transaction transaction : transactions) {
            String categoryName =
                    categoryService.getCategoryNameById(
                            transaction.getCategoryId());

            model.addRow(new Object[]{
                transaction.getId(),
                transaction.getAmount(),
                categoryName,
                transaction.getDescription(),
                transaction.getTransactionDate()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cmboIncomeCategory = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        incomeAmountField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        incomeTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        incomeDescriptionTextArea = new javax.swing.JTextArea();
        updateIncomeButton = new javax.swing.JButton();
        clearIncomeButton = new javax.swing.JButton();
        deleteIncomeButton = new javax.swing.JButton();
        addIncomeButton = new javax.swing.JButton();
        btnAddIncomeCategory = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(882, 620));

        jPanel1.setBackground(new java.awt.Color(220, 232, 208));
        jPanel1.setMaximumSize(null);
        jPanel1.setPreferredSize(new java.awt.Dimension(1020, 604));
        jPanel1.setRequestFocusEnabled(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(111, 151, 143));
        jLabel2.setText("Category");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(111, 151, 143));
        jLabel1.setText("Amount");

        jScrollPane1.setBackground(new java.awt.Color(220, 232, 208));

        incomeTable.setBackground(new java.awt.Color(220, 232, 208));
        incomeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Amount", "Category", "Description", "Date"
            }
        ));
        incomeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                incomeTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(incomeTable);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(111, 151, 143));
        jLabel3.setText("Notes");

        incomeDescriptionTextArea.setColumns(20);
        incomeDescriptionTextArea.setRows(5);
        incomeDescriptionTextArea.setText("\n\n");
        jScrollPane2.setViewportView(incomeDescriptionTextArea);

        updateIncomeButton.setBackground(new java.awt.Color(111, 151, 143));
        updateIncomeButton.setForeground(new java.awt.Color(242, 242, 242));
        updateIncomeButton.setText("Update");
        updateIncomeButton.addActionListener(this::updateIncomeButtonActionPerformed);

        clearIncomeButton.setBackground(new java.awt.Color(111, 151, 143));
        clearIncomeButton.setForeground(new java.awt.Color(242, 242, 242));
        clearIncomeButton.setText("Clear");
        clearIncomeButton.addActionListener(this::clearIncomeButtonActionPerformed);

        deleteIncomeButton.setBackground(new java.awt.Color(111, 151, 143));
        deleteIncomeButton.setForeground(new java.awt.Color(242, 242, 242));
        deleteIncomeButton.setText("Delete");
        deleteIncomeButton.addActionListener(this::deleteIncomeButtonActionPerformed);

        addIncomeButton.setBackground(new java.awt.Color(111, 151, 143));
        addIncomeButton.setForeground(new java.awt.Color(242, 242, 242));
        addIncomeButton.setText("Add");
        addIncomeButton.addActionListener(this::addIncomeButtonActionPerformed);

        btnAddIncomeCategory.setBackground(new java.awt.Color(111, 151, 143));
        btnAddIncomeCategory.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAddIncomeCategory.setForeground(new java.awt.Color(242, 242, 242));
        btnAddIncomeCategory.setText("+");
        btnAddIncomeCategory.addActionListener(this::btnAddIncomeCategoryActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(incomeAmountField, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cmboIncomeCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAddIncomeCategory)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                            .addComponent(addIncomeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(updateIncomeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deleteIncomeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(clearIncomeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(57, 57, 57))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addIncomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(updateIncomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteIncomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(clearIncomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAddIncomeCategory)
                            .addComponent(cmboIncomeCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1)
                        .addGap(12, 12, 12)
                        .addComponent(incomeAmountField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 882, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtfldIncomeAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfldIncomeAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfldIncomeAmountActionPerformed

    private void incomeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_incomeTableMouseClicked
        int row = incomeTable.getSelectedRow();
        
        if (row == -1) {
            return;
        }
        selectedTransactionId =
                Integer.parseInt(incomeTable.getValueAt(row, 0).toString());
        incomeAmountField.setText(incomeTable.getValueAt(row, 1).toString());

        String categoryName = incomeTable.getValueAt(row, 2).toString();

        for (int i = 0; i < cmboIncomeCategory.getItemCount(); i++) {
            Category category = cmboIncomeCategory.getItemAt(i);
            if (category.getName().equals(categoryName)) {
                cmboIncomeCategory.setSelectedIndex(i);
                break;
            }
        }
        incomeDescriptionTextArea.setText(
                incomeTable.getValueAt(row, 3).toString());
    }//GEN-LAST:event_incomeTableMouseClicked

    private void updateIncomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateIncomeButtonActionPerformed
       if (selectedTransactionId == -1) {
        JOptionPane.showMessageDialog(this, "Please select a transaction first.");
        return;
    }

    try {
        Category category =
                (Category) cmboIncomeCategory.getSelectedItem();

        BigDecimal amount =
                new BigDecimal(incomeAmountField.getText());

        String description =
                incomeDescriptionTextArea.getText();

        Transaction transaction = new Transaction();

        transaction.setId(selectedTransactionId);
        transaction.setCategoryId(category.getId());    
        transaction.setAmount(amount);
        transaction.setDescription(description);

        TransactionService service = new TransactionService();

        if (service.updateTransaction(transaction)) {
            JOptionPane.showMessageDialog(this, "Income updated successfully!");
            loadIncomeTable();
            clearIncomeButton.doClick();
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Invalid amount.");
    }
    }//GEN-LAST:event_updateIncomeButtonActionPerformed

    private void clearIncomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearIncomeButtonActionPerformed
       incomeAmountField.setText("");

        incomeDescriptionTextArea.setText("");

        if (cmboIncomeCategory.getItemCount() > 0)
            cmboIncomeCategory.setSelectedIndex(0);
        incomeTable.clearSelection();

        selectedTransactionId = -1;
    }//GEN-LAST:event_clearIncomeButtonActionPerformed

    private void deleteIncomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteIncomeButtonActionPerformed
       if (selectedTransactionId == -1) {
        JOptionPane.showMessageDialog(this, "Please select a transaction.");
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(this,
            "Delete this income?",
            "Confirm",
            JOptionPane.YES_NO_OPTION);

    if (confirm == JOptionPane.YES_OPTION) {
        TransactionService service = new TransactionService();

        if (service.deleteTransaction(selectedTransactionId)) {
            JOptionPane.showMessageDialog(this, "Income deleted.");
            loadIncomeTable();
            clearIncomeButton.doClick();
        }
    }
    }//GEN-LAST:event_deleteIncomeButtonActionPerformed

    private void addIncomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addIncomeButtonActionPerformed
        try {
            Category category =
                    (Category) cmboIncomeCategory.getSelectedItem();

            if (category == null) {
                JOptionPane.showMessageDialog(this, "Please select a category.");
                return;
            }
            BigDecimal amount = new BigDecimal(incomeAmountField.getText().trim());

            String description = incomeDescriptionTextArea.getText().trim();

            Transaction transaction = new Transaction();

            transaction.setUserId(Session.getCurrentUser().getId());
            transaction.setCategoryId(category.getId());
            transaction.setType("income");
            transaction.setAmount(amount);
            transaction.setDescription(description);
    
            transaction.setTransactionDate(
                    java.sql.Date.valueOf(java.time.LocalDate.now()));

            TransactionService service = new TransactionService();

            if (service.addTransaction(transaction)) {
                JOptionPane.showMessageDialog(this, "Income added successfully!");

                loadIncomeTable();

                incomeAmountField.setText("");
                incomeDescriptionTextArea.setText("");

                if (cmboIncomeCategory.getItemCount() > 0) {
                    cmboIncomeCategory.setSelectedIndex(0);
                }
                incomeTable.clearSelection();
                selectedTransactionId = -1;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Invalid amount.");
        }
    }//GEN-LAST:event_addIncomeButtonActionPerformed

    private void btnAddIncomeCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddIncomeCategoryActionPerformed
            String categoryName = JOptionPane.showInputDialog(this, "Enter new income category:");

        if (categoryName == null) {
            return;
        }

        categoryName = categoryName.trim();

        if (categoryName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Category name cannot be empty.");
            return;
        }

        CategoryService categoryService = new CategoryService();

        int userId = Session.getCurrentUser().getId();

        if (categoryService.categoryExists(userId, categoryName, "income")) {
            JOptionPane.showMessageDialog(this, "Category already exists.");
            return;
        }

        Category category = new Category();

        category.setUserId(userId);
        category.setName(categoryName);
        category.setType("income");

        if (categoryService.addCategory(category)) {
            JOptionPane.showMessageDialog(this, "Category added successfully.");

            loadIncomeCategories();

            // Automatically select the newly added category
            for (int i = 0; i < cmboIncomeCategory.getItemCount(); i++) {
                Category c = cmboIncomeCategory.getItemAt(i);

                if (c.getName().equalsIgnoreCase(categoryName)) {
                    cmboIncomeCategory.setSelectedIndex(i);
                    break;
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Failed to add category.");
        }
    }//GEN-LAST:event_btnAddIncomeCategoryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addIncomeButton;
    private javax.swing.JButton btnAddIncomeCategory;
    private javax.swing.JButton clearIncomeButton;
    private javax.swing.JComboBox<Category> cmboIncomeCategory;
    private javax.swing.JButton deleteIncomeButton;
    private javax.swing.JTextField incomeAmountField;
    private javax.swing.JTextArea incomeDescriptionTextArea;
    private javax.swing.JTable incomeTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton updateIncomeButton;
    // End of variables declaration//GEN-END:variables
}
